name: helloGithubAction

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: print name.py
      run: python name.py
      
    - name: pip upgrade
      run: python -m pip install --upgrade pip
      
    - name: install required packages
      run: pip install -r requirements.txt
      
    - name: run python
      run: python test.py
